<a href="https://colab.research.google.com/github/AatiqahHarmine/2303A51860_B30_PDS/blob/main/Assignment3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Create 2-D Array

In [1]:
import numpy as np

test_scores = np.random.randint(0, 101, size=(4, 4))
print(test_scores)

[[15 59 52 79]
 [49 11 97 54]
 [72 95 40 52]
 [75  4  2 88]]


In [2]:
column_means = np.mean(test_scores, axis=0)
row_means = np.mean(test_scores, axis=1)

print("Column-wise means:", column_means)
print("Row-wise means:", row_means)

Column-wise means: [52.75 42.25 47.75 68.25]
Row-wise means: [51.25 52.75 64.75 42.25]


In [3]:
std_dev = np.std(test_scores)
variance = np.var(test_scores)

print("Standard Deviation:", std_dev)
print("Variance:", variance)

Standard Deviation: 30.494876618868293
Variance: 929.9375


In [4]:
min_value = np.min(test_scores)
max_value = np.max(test_scores)
min_index = np.argmin(test_scores)
max_index = np.argmax(test_scores)

print("Minimum value:", min_value)
print("Maximum value:", max_value)
print("Index of minimum value:", min_index)
print("Index of maximum value:", max_index)

Minimum value: 2
Maximum value: 97
Index of minimum value: 14
Index of maximum value: 6


In [5]:
print("Statistical Analysis Summary:")
print("----------------------------")
print(f"Row-wise means: {row_means}")
print(f"Column-wise means: {column_means}")
print(f"Overall Standard Deviation: {std_dev}")
print(f"Overall Variance: {variance}")
print(f"Global Minimum Value: {min_value} (Index: {min_index})")
print(f"Global Maximum Value: {max_value} (Index: {max_index})")

Statistical Analysis Summary:
----------------------------
Row-wise means: [51.25 52.75 64.75 42.25]
Column-wise means: [52.75 42.25 47.75 68.25]
Overall Standard Deviation: 30.494876618868293
Overall Variance: 929.9375
Global Minimum Value: 2 (Index: 14)
Global Maximum Value: 97 (Index: 6)


## Create 3d array


In [6]:
rgb_image = np.random.randint(0, 256, size=(3, 3, 3))
print(rgb_image)

[[[130 205  50]
  [149 236 133]
  [246 242 152]]

 [[157 173  91]
  [170 106  94]
  [ 49  57  79]]

 [[120 144  81]
  [163 212 217]
  [ 92  70  49]]]


In [7]:
red_channel = rgb_image[:, :, 0]
green_channel = rgb_image[:, :, 1]
blue_channel = rgb_image[:, :, 2]

print("Red Channel:\n", red_channel)
print("Green Channel:\n", green_channel)
print("Blue Channel:\n", blue_channel)

Red Channel:
 [[130 149 246]
 [157 170  49]
 [120 163  92]]
Green Channel:
 [[205 236 242]
 [173 106  57]
 [144 212  70]]
Blue Channel:
 [[ 50 133 152]
 [ 91  94  79]
 [ 81 217  49]]


In [8]:
red_mean = np.mean(red_channel)
green_mean = np.mean(green_channel)
blue_mean = np.mean(blue_channel)

print(f"Average pixel intensity for Red channel: {red_mean}")
print(f"Average pixel intensity for Green channel: {green_mean}")
print(f"Average pixel intensity for Blue channel: {blue_mean}")

Average pixel intensity for Red channel: 141.77777777777777
Average pixel intensity for Green channel: 160.55555555555554
Average pixel intensity for Blue channel: 105.11111111111111


In [9]:
brightness_increase = 50
brightened_image = np.clip(rgb_image + brightness_increase, 0, 255)
print("Brightened Image (clipped at 255):\n", brightened_image)

Brightened Image (clipped at 255):
 [[[180 255 100]
  [199 255 183]
  [255 255 202]]

 [[207 223 141]
  [220 156 144]
  [ 99 107 129]]

 [[170 194 131]
  [213 255 255]
  [142 120  99]]]


In [11]:
print("Statistical Analysis Summary:")
print("----------------------------")
print("Red Channel:\n", red_channel)
print("Green Channel:\n", green_channel)
print("Blue Channel:\n", blue_channel)
print(f"\nAverage pixel intensity for Red channel: {red_mean}")
print(f"Average pixel intensity for Green channel: {green_mean}")
print(f"Average pixel intensity for Blue channel: {blue_mean}")
print("\nBrightened Image (clipped at 255):\n", brightened_image)

Statistical Analysis Summary:
----------------------------
Red Channel:
 [[130 149 246]
 [157 170  49]
 [120 163  92]]
Green Channel:
 [[205 236 242]
 [173 106  57]
 [144 212  70]]
Blue Channel:
 [[ 50 133 152]
 [ 91  94  79]
 [ 81 217  49]]

Average pixel intensity for Red channel: 141.77777777777777
Average pixel intensity for Green channel: 160.55555555555554
Average pixel intensity for Blue channel: 105.11111111111111

Brightened Image (clipped at 255):
 [[[180 255 100]
  [199 255 183]
  [255 255 202]]

 [[207 223 141]
  [220 156 144]
  [ 99 107 129]]

 [[170 194 131]
  [213 255 255]
  [142 120  99]]]
